name = "z-interact"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "z_interact_db"
database_name = "z-interact-db"
database_id = "42c899ea-ff0f-4c9e-adfd-bcd3a4ae4ffa"